apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
data:
  pat-github: QmFzaWMgWkdWMmIzQnpXVzg2WjJod1gxaE9VWFV6Y0cxM1pVNUVXVUZIVEVONFVEaFllbFJuYkVKR1JWRnhVakJwWlhsTVRRPT0=