apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner-set-apig
  namespace: argocd
spec:
  project: cmdo-project
  source:
    repoURL: "https://github.com/devopsYo/arc.git"
    targetRevision: "HEAD"
    path: "arc-runner-set"
    helm:
      valueFiles:
        - env/dev/apig-values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "cmdo-arc-runners-apig"
  syncPolicy: {}