apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-app
  namespace: argocd
spec:
  project: cmdo-project
  source:
    repoURL: "https://github.com/devopsYo/arc.git"
    targetRevision: "HEAD"
    path: "arc"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "cmdo-arc-systems"
  syncPolicy: {}