apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-app
  namespace: argocd
spec:
  project: cmdo-project
  source:
    repoURL: "https://github.com/devopsYo/argo-workflows.git"
    targetRevision: "HEAD"
    path: "."
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "argo"
  syncPolicy: {}