apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-cd-workflows
  namespace: argocd
spec:
  project: cmdo-project
  source:
    repoURL: "https://github.com/devopsYo/argo-workflows.git"
    targetRevision: "HEAD"
    path: "workflows/ci-cd-workflows"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "argo"
  syncPolicy: {}