apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: cmdo-project
  source:
    repoURL: "https://github.com/devopsYo/nginx.git"
    targetRevision: "HEAD"
    path: "."
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "nginx"
  syncPolicy: {}