apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: CreateNamespace=true
spec:
  project: default
  source:
    repoURL: "https://github.com/devopsYo/arc.git"
    targetRevision: "HEAD"
    path: "arc"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "arc-systems"
  syncPolicy: {}